def generate_code(description, board, language):
    d = description.lower()
    uses_ultrasonic = any(x in d for x in ["ultrasonic", "distance sensor", "hc-sr04"])
    uses_servo = "servo" in d
    uses_motor = any(x in d for x in ["motor", "wheel", "rover", "car", "robot"])
    lines = [
        f"// RoboLab generated starter code",
        f"// Project: {description}",
        f"// Board: {board}",
        "",
    ]
    if "arduino" in board.lower():
        lines += ["void setup() {", "  Serial.begin(115200);"]
        if uses_servo: lines += ["  // Servo initialization goes here."]
        if uses_motor: lines += ["  // Motor driver initialization goes here."]
        lines += ["}", "", "void loop() {"]
        if uses_ultrasonic:
            lines += ["  // Read ultrasonic distance here.", "  // Add your safe distance threshold."]
        if uses_servo:
            lines += ["  // Set servo position based on your control logic."]
        if uses_motor:
            lines += ["  // Drive motors according to the project state."]
        lines += ["  delay(50);", "}"]
    else:
        lines += [f"# {language} starter generated by RoboLab", "# Add the board-specific SDK/API here."]
    return {
        "board": board,
        "language": language,
        "code": "\n".join(lines),
        "notes": [
            "This is a safe, editable starter generated from the project description.",
            "Verify pins, voltage/current limits, libraries, and hardware before connecting a real device."
        ]
    }
