from __future__ import annotations

# Lightweight, vendor-neutral component ontology for natural-language recognition.
# It intentionally preserves unknown user-supplied parts instead of rejecting them.
COMPONENT_CATALOG = {
    "Arduino Uno": ("controller", ["arduino uno", "uno r3", "arduino uno r3", "uno"]),
    "Arduino Nano": ("controller", ["arduino nano", "nano"]),
    "Arduino Mega": ("controller", ["arduino mega", "mega 2560", "arduino mega 2560"]),
    "ESP32": ("controller", ["esp32", "esp 32"]),
    "ESP8266": ("controller", ["esp8266", "esp 8266"]),
    "Raspberry Pi": ("computer", ["raspberry pi", "raspi", "rpi", "pi zero", "pi 4", "pi 5"]),
    "STM32 board": ("controller", ["stm32", "stm 32", "nucleo", "stm32 nucleo"]),
    "microcontroller": ("controller", ["microcontroller", "mcu", "controller board"]),
    "HC-SR04 ultrasonic sensor": ("sensor", ["hc-sr04", "hc sr04", "ultrasonic", "ultrasonic sensor", "distance sensor", "sonar sensor"]),
    "IR obstacle sensor": ("sensor", ["ir obstacle", "ir sensor", "infrared sensor", "ir obstacle sensor"]),
    "line sensor": ("sensor", ["line sensor", "line follower", "line following", "line tracking", "reflective sensor", "ir array"]),
    "flame sensor": ("sensor", ["flame sensor", "flame detector", "fire sensor", "fire detector", "flame ir"]),
    "smoke/gas sensor": ("sensor", ["smoke sensor", "gas sensor", "mq-2", "mq2", "mq-135", "mq135", "air quality sensor"]),
    "temperature sensor": ("sensor", ["temperature sensor", "thermistor", "ds18b20", "lm35", "tmp36", "dht11", "dht22"]),
    "humidity sensor": ("sensor", ["humidity sensor", "dht11", "dht22"]),
    "IMU": ("sensor", ["imu", "mpu6050", "mpu-6050", "mpu9250", "mpu-9250", "gyroscope", "gyro", "accelerometer"]),
    "wheel encoder": ("sensor", ["encoder", "wheel encoder", "rotary encoder", "quadrature encoder"]),
    "GPS/GNSS": ("sensor", ["gps", "gnss", "neo-6m", "neo6m", "gps module"]),
    "camera": ("sensor", ["camera", "camera module", "webcam", "vision", "pi camera"]),
    "lidar": ("sensor", ["lidar", "laser scanner", "2d lidar", "3d lidar"]),
    "microphone": ("sensor", ["microphone", "mic", "sound sensor"]),
    "LDR/light sensor": ("sensor", ["ldr", "light sensor", "photoresistor", "photocell"]),
    "proximity sensor": ("sensor", ["proximity sensor", "proximity detector"]),
    "touch sensor": ("sensor", ["touch sensor", "capacitive touch"]),
    "pressure sensor": ("sensor", ["pressure sensor", "barometer", "bmp280", "bme280"]),
    "current sensor": ("sensor", ["current sensor", "ina219", "ina226", "hall current sensor"]),
    "voltage sensor": ("sensor", ["voltage sensor", "voltage divider module"]),
    "DC gearmotor": ("actuator", ["dc motor", "dc gearmotor", "gear motor", "geared motor", "motor", "wheel motor"]),
    "servo motor": ("actuator", ["servo", "servo motor", "sg90", "mg90s", "mg996r"]),
    "stepper motor": ("actuator", ["stepper", "stepper motor", "nema 17", "nema17"]),
    "brushless motor": ("actuator", ["brushless", "brushless motor", "bldc", "bldc motor"]),
    "pump": ("actuator", ["pump", "water pump", "mini pump", "peristaltic pump"]),
    "fan": ("actuator", ["fan", "blower", "cooling fan"]),
    "solenoid": ("actuator", ["solenoid", "solenoid valve"]),
    "relay": ("switching", ["relay", "relay module", "5v relay", "solid state relay", "ssr"]),
    "buzzer": ("output", ["buzzer", "beeper", "piezo"]),
    "LED": ("output", ["led", "leds", "rgb led", "neopixel", "ws2812", "ws2812b"]),
    "LCD/OLED display": ("output", ["lcd", "oled", "display", "screen", "i2c lcd", "i2c oled"]),
    "L298N motor driver": ("driver", ["l298n", "l298", "h bridge", "h-bridge", "motor driver"]),
    "TB6612FNG motor driver": ("driver", ["tb6612", "tb6612fng", "dual motor driver"]),
    "PCA9685 servo driver": ("driver", ["pca9685", "servo driver"]),
    "ESC": ("driver", ["esc", "electronic speed controller"]),
    "buck converter": ("power", ["buck converter", "step down", "dc-dc step down", "dcdc step down"]),
    "boost converter": ("power", ["boost converter", "step up", "dc-dc step up"]),
    "voltage regulator": ("power", ["voltage regulator", "linear regulator", "ldo", "5v regulator", "3.3v regulator"]),
    "battery": ("power", ["battery", "battery pack", "rechargeable battery"]),
    "Li-ion battery": ("power", ["li-ion", "li ion", "lithium ion", "18650"]),
    "LiPo battery": ("power", ["lipo", "li-po", "lithium polymer"]),
    "9V battery": ("power", ["9v battery", "9 volt battery", "pp3"]),
    "AA battery pack": ("power", ["aa battery", "aa batteries", "battery holder"]),
    "USB power bank": ("power", ["power bank", "usb power", "usb supply", "5v usb"]),
    "breadboard": ("prototyping", ["breadboard", "solderless breadboard", "prototype board"]),
    "jumper wires": ("wiring", ["jumper wires", "dupont wires", "male male", "male female", "female female"]),
    "resistor": ("passive", ["resistor", "resistors", "pullup", "pull-up", "pull down", "pull-down"]),
    "capacitor": ("passive", ["capacitor", "capacitors", "electrolytic capacitor", "ceramic capacitor"]),
    "diode": ("passive", ["diode", "flyback diode", "rectifier"]),
    "transistor": ("active", ["transistor", "bjt", "npn", "pnp"]),
    "MOSFET": ("active", ["mosfet", "n mosfet", "p mosfet"]),
    "push button": ("input", ["button", "push button", "pushbutton", "switch"]),
    "potentiometer": ("input", ["potentiometer", "pot", "variable resistor"]),
    "Bluetooth module": ("connectivity", ["bluetooth", "hc-05", "hc05", "hc-06", "hc06"]),
    "Wi-Fi module": ("connectivity", ["wifi", "wi-fi", "wifi module"]),
    "RF module": ("connectivity", ["rf module", "radio module", "nrf24l01", "433mhz"]),
    "LoRa module": ("connectivity", ["lora", "lora module"]),
    "Ethernet": ("connectivity", ["ethernet", "lan"]),
    "chassis/frame": ("mechanical", ["chassis", "frame", "robot chassis", "base plate", "body"]),
    "wheel": ("mechanical", ["wheel", "wheels", "omni wheel", "mecanum wheel", "caster"]),
    "gear": ("mechanical", ["gear", "gears", "gearbox", "gear train"]),
    "bearing": ("mechanical", ["bearing", "bearings"]),
    "belt": ("mechanical", ["belt", "timing belt", "rubber belt"]),
    "pulley": ("mechanical", ["pulley", "pulleys"]),
    "screw/bolt/fastener": ("mechanical", ["screw", "screws", "bolt", "bolts", "nut", "nuts", "fastener", "fasteners"]),
    "3D-printed part": ("mechanical", ["3d printed", "3d print", "printed part", "pla", "petg"]),
}
